// Auto-generated by CI. Do not edit manually.
// In CI, this file is overwritten with the actual version.
// For local development, a default version is used.
namespace ExcelEntityExporter;

internal static class VersionInfo
{
    public const string Version = "dev-local";
}
